### ISSUE TITLE
Is there a way to test the sql connection in Linux?

### ISSUE THREAD

**Issue by JoemerRamos** [SafetyCulture/iauditor-exporter#116]
See topic above, I was wondering if there was a command to test the sql connection

**Comment by hkf57** [comment]
Hi @JoemerRamos, that is a great suggestion. Unfortunately at the moment we don't support this functionality. We welcome any contributions if you would like to add it to the product.

Meanwhile I have added it to the our internal backlog and it will be prioritised as such.
