### ISSUE TITLE
Action Data Exporter.py Issue

### ISSUE THREAD

**Issue by JoemerRamos** [SafetyCulture/iauditor-exporter#12]
When using format --actions-sql, there is currently a bug where if the entry already exists, we get a primary key error on an insert and it doesn't update the row and ends the script execution. 

![image](https://user-images.githubusercontent.com/34356209/91457690-a156bd00-e852-11ea-90c4-a5e423f13c8e.png)

**Comment by BCook98** [comment]
Hi @JoemerRamos. We've released a new major version of iAuditor Exporter which includes updates to the way Actions are exported.

Take a look at https://github.com/SafetyCulture/iauditor-exporter and https://help.safetyculture.com/en_us/1064272525-rJ3PYPFEP for more details.

**Comment by JoemerRamos** [comment]
Going to try using the new version
