### ISSUE TITLE
Web Link Not Public

### ISSUE THREAD

**Issue by bricwood** [SafetyCulture/iauditor-exporter#136]
The former CSV exporter tool allowed the export of Web Links which were publicly accessible.

We have migrated to the new tool with DB support however these links require login and are not publicly accessible.

**Comment by hkf57** [comment]
Hi @bricwood , thanks for raising this. This is something we're aware of and are actively working towards.

Unfortunately I can't give you an ETA for this feature, but it is one of the common asks for those upgrading from v2 to v3, so it will be prioritised within our team accordingly.

**Comment by hkf57** [comment]
Hi @bricwood . We have released version [3.4.0](https://github.com/SafetyCulture/iauditor-exporter/releases/tag/v3.4.0) which contains the ability to generate public report links. It uses the same mechanism as the v2 python exporter.

Please give it a go and let us know if it doesn't meet your needs.
