### ISSUE TITLE
Inspections table not updating when archived

### ISSUE THREAD

**Issue by bricwood** [SafetyCulture/iauditor-exporter#185]
I do not get any results when querying our **inspections** table for **archived** that does not equal 0.

We have a number of archived inspections however this is not reflected in the table.

**Comment by BCook98** [comment]
@bricwood are you still experiencing this issue after implementing @eddabrahamsen's suggestion?

**Comment by hkf57** [comment]
Hi @bricwood , please let us know if @eddabrahamsen did not resolve your issue. Thanks!
