### ISSUE TITLE
Mandatory columns not correspond to previous version

### ISSUE THREAD

**Issue by vlachodc** [SafetyCulture/iauditor-exporter#221]
I exported data from iAuditor to csv files, using the new version of iAuditor-exporter. I found a problem in inspection_items.csv, where more columns are added in the middle before to "mandatory" column name, thus, exporting csv to local database not correspond to properly locations in previous version.
Thks

**Comment by MickStanciu** [comment]
Hi @vlachodc ,
I can see the use case you are mentioning.
iAuditor exporter is using an internal SQLlite (would be in the exports directory as sqlite.db) and whenever there is a schema change, that would also change.
Exporting to CSV: the cvs files are recreated every export.
Another approach we suggest is exporting to SQL directly. For example, in iauditor-exporter.yaml can add the following (with your correct db connection strings)
`
db:
  connection_string: "postgresql://postgres:secret@localhost:5432/iauditor_db"
  dialect: postgres
`
Calling `iauditor-exporter sql` will append to this database all the new information.
If there is a schema change, and happens to be anywhere, the column will be appended at the end (for SQL).
