### ISSUE TITLE
Cannot find requirement in Python 3.6

### ISSUE THREAD

**Issue by castsolutionsau** [SafetyCulture/iauditor-exporter#8]
Has the Python version changed to minimum 3.7+ with the latest release?
We're on 3.6 but get "Could not find a version that satisfies the requirement safetyculture-sdk-python-beta>=2.1.1 (from -r requirements.txt (line 11)) (from versions: 1.0.3, 1.1, 1.2, 2.0, 2.0.1)
No matching distribution found for safetyculture-sdk-python-beta>=2.1.1 (from -r requirements.txt (line 11))" when pip'ng the requirements

According to the PyPi docs, "Requires: Python >=3.7, <4.0" for 2.1.x, whereas the older version (2.0.x) listed a min Python installation of 3.6

**Comment by eddabrahamsen** [comment]
Hey! Apologies for not getting back to you on this sooner - Github doesn't seem to be notifying me of new issues. This was a mistake on my part when repackaging the SDK. I've just published a new version to PyPi (2.1.2) which will work with 3.5+ so you should be okay to use that. I'll close for now but let me know if any issues.
