### ISSUE TITLE
v3.0.3 Exception Error on startup/run the tool

### ISSUE THREAD

**Issue by AtlasFMChrisWeeks** [SafetyCulture/iauditor-exporter#95]
Running 3.0.3 tool produces the below error after a clean download has been extracted to a new folder.  I will roll back to the previous version in the meantime. 

PS C:\iAuditor\Smith & Williamson Quality Audit & KPI V2> ./iauditor-exporter configure
Exception 0xc0000005 0x0 0x7ff894eb0fff 0x1990000
PC=0x1990000
signal arrived during external code execution

syscall.getprocaddress(0x7ff86fa40000, 0xc0001fc840, 0x0, 0x0)
        /usr/local/go/src/runtime/syscall_windows.go:171 +0xe5
syscall.(*DLL).FindProc(0xc0001f3d20, 0xf837a4, 0x16, 0x73e821b3f9cf4b02, 0x2c000000015d9100, 0x0)
        /usr/local/go/src/syscall/dll_windows.go:115 +0x96
syscall.(*LazyProc).Find(0xc000209b30, 0x0, 0x0)
        /usr/local/go/src/syscall/dll_windows.go:304 +0xfa
syscall.(*LazyProc).mustFind(...)
        /usr/local/go/src/syscall/dll_windows.go:318
syscall.(*LazyProc).Call(0xc000209b30, 0x0, 0x0, 0x0, 0xf7a058, 0x9, 0x107dae0, 0x15d6bd0)
        /usr/local/go/src/syscall/dll_windows.go:336 +0x36
github.com/denisenkom/go-mssqldb.init.1()
        /go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20200428022330-06a60b6afbbc/sspi_windows.go:17 +0x45
rax     0x7ff891aaef06
rbx     0x7ff891aaef04
rcx     0x5f
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x181fa00
rsp     0x181f4b0
r8      0x0
r9      0x0
r10     0x0
r11     0x94b
r12     0x7ff894cc0000
r13     0x0
r14     0x7ff891aaef06
r15     0xc000007a
rip     0x1990000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

**Comment by phanikumarpatchigolla** [comment]
@AtlasFMChrisWeeks Thanks for reporting this issue.
Can you please provide the following information:
1. Is this occurring only with `configure` command ? Are you able to run `help` command ?
2. Also, can you specify on which Windows OS version has this issue occurred.

**Comment by AtlasFMChrisWeeks** [comment]
> @AtlasFMChrisWeeks Thanks for reporting this issue.
> Can you please provide the following information:
> 
> 1. Is this occurring only with `configure` command ? Are you able to run `help` command ?
> 2. Also, can you specify on which Windows OS version has this issue occurred.

Hi,  I have re-downloaded the latest version and it seems to be running successfully this time with both the configure, help and report functions.  
I was on Windows 10 1909 i believe.  I have since updated to the latest win10 update this week so i am now on 20H2.  it is a 64bit version.  

I do also get the following error in both versions though;

PDF export failed for 'PG Belfast Lisburn Laganbank / 28 Jul 2020 / Gary Farren - local copy'. Error: PDF report generation for PG Belfast Lisburn Laganbank / 28 Jul 2020 / Gary Farren - local copy terminated after 15 tries

the above error doesnt seem to be every single report though, just random ones by the way it looks.  

I believe our iAuditor subscription ends soon which is why we are extracting the reports into pdf format. I may not be able to help too much with diagnosing these errors once the subscription ends.  Do let me know if I can help in any way though.

**Comment by atashbahar** [comment]
Hi @AtlasFMChrisWeeks, great to hear the tool is working for you now. 
Regarding the error you are getting. Does the error happen again for the same inspection when you retry or does it happen randomly?

**Comment by hkf57** [comment]
Hi @AtlasFMChrisWeeks , please re-open the issue if it's continuing to be a problem!
